[package]
name = "stress4844"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.25"
ethers = "1.0.0"
eyre = "0.6.8"
tokio = { version = "1.21.2", features = ["macros"] }
